export const siteConfig = {
  name: "MORA",
  tagline: "Specialty Coffee & Fresh Bakes",
  description:
    "An artisanal European-inspired café dedicated to slow mornings, expressive specialty coffees, and freshly baked pastries.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://mora-cafe.example.com",
  ogImage: "/images/hero-coffee-pastry.jpg",
  contact: {
    email: "hello@moracafe.example",
    phone: "+91 80 4123 4567",
  },
  location: {
    street: "12 Example Street",
    locality: "Indiranagar",
    city: "Bengaluru",
    region: "Karnataka",
    postalCode: "560038",
    country: "India",
    fullAddress: "12 Example Street, Indiranagar, Bengaluru, India",
    directionsUrl: "https://maps.google.com/?q=MORA+Specialty+Coffee",
  },
  hours: [
    { days: "Monday — Friday", time: "8:00 AM — 8:00 PM" },
    { days: "Saturday — Sunday", time: "9:00 AM — 9:00 PM" },
  ],
  social: {
    instagram: "https://instagram.com/moracafe.demo",
    threads: "https://threads.net/@moracafe.demo",
  },
  navLinks: [
    { label: "Menu", href: "#menu" },
    { label: "About", href: "#about" },
    { label: "Story", href: "#story" },
    { label: "Space", href: "#space" },
    { label: "Gallery", href: "#gallery" },
    { label: "Visit", href: "#visit" },
  ],
  popularDrinks: [
    {
      id: "signature-latte",
      name: "Signature Latte",
      price: "₹220",
      description: "Silky steamed whole milk with a double ristretto of our medium-roast house blend.",
      image: "/images/drink-latte.jpg",
      tag: "House Favorite",
    },
    {
      id: "ceremonial-matcha",
      name: "Ceremonial Matcha",
      price: "₹240",
      description: "First-harvest Uji ceremonial matcha hand-whisked and paired with velvety oat milk.",
      image: "/images/drink-matcha.jpg",
      tag: "Single Origin",
    },
    {
      id: "dark-mocha",
      name: "Dark Mocha",
      price: "₹250",
      description: "70% single-origin bean-to-bar dark chocolate melted into espresso and microfoam.",
      image: "/images/drink-mocha.jpg",
      tag: "Indulgent",
    },
  ],
  bakeryItems: [
    {
      id: "butter-croissant",
      name: "Butter Croissant",
      category: "Laminated Viennoiserie",
      price: "₹180",
      description: "Flaky, golden, and baked fresh each morning using cultured French butter.",
      image: "/images/food-croissant.jpg",
      featured: true,
    },
    {
      id: "berry-cheesecake",
      name: "Berry Cheesecake",
      category: "Patisserie",
      price: "₹260",
      description: "Creamy, delicate, and finished with fresh seasonal berries on a crisp sablé crust.",
      image: "/images/food-cheesecake.jpg",
      featured: false,
    },
    {
      id: "chocolate-cookie",
      name: "Chocolate Cookie",
      category: "Baked Good",
      price: "₹150",
      description: "Crisp edges, soft chewy center, and generous pools of 65% dark chocolate chunks.",
      image: "/images/food-cookie.jpg",
      featured: false,
    },
  ],
};
